### ISSUE TITLE
Extend HTTP probe type to support more complex probes

### ISSUE THREAD

**Issue by MrAlias** [google/cloudprober#129]
It would be useful if the HTTP probe was extended to supported the following:

- All HTTP method types (`GET`, `POST`, `PUT`, `HEAD`, `DELETE`, `PATCH`, `OPTIONS`).
- Request bodies.
- Arbitrary headers.

Being able to customize HTTP requests in these ways would allow for a more comprehensive probe into a system in line with normal user behavior.

**Comment by manugarg** [comment]
Fixed in the commit 2ac8624.
