### ISSUE TITLE
Add support for histograms/distributions

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#13]
Cloudprober's metrics package should support histograms value types.

**Comment by manugarg** [comment]
Commit #db3fc31 adds a DISTRIBUTION type cloudprober's metrics library.

**Comment by manugarg** [comment]
Commit 079d723 adds support for specifying Distributions through a protobuf and extends probe config protobuf to add an option to use Distributions for latency.

**Comment by manugarg** [comment]
Commit 5397a37 adds Distributions support to HTTP probe.

**Comment by manugarg** [comment]
Commit ef29283 adds support for exporting distributions over prometheus.

**Comment by manugarg** [comment]
This is now complete. Screenshot of latency distribution in stackdriver:

![cloudprober distributions stackdriver](https://user-images.githubusercontent.com/1286425/33115914-9beb30aa-cf17-11e7-82c5-3f9ef34bb9f9.png)

**Comment by manugarg** [comment]
Couple of more commits for this issue: 
f114067 -- Add distributions support to external probe type.
c018e5c -- Add a method to parse distributions from a string (same format as Distribution.String()).

**Comment by manugarg** [comment]
Latest release 0.9.3 include these changes.

**Comment by Beatrice7** [comment]
should add a sample.
