### ISSUE TITLE
Postgres Surfacer

### ISSUE THREAD

**Issue by dmicanzerofox** [google/cloudprober#130]
Currently, I am auditing using cloudprober with prometheus and [postgres remote endpoint](https://github.com/timescale/prometheus-postgresql-adapter).  It would simplify things drastically to be able to write to postgres directly from cloudprober.  I would be happy to contribute this if it's something that could be in cloudprober.

**Comment by manugarg** [comment]
Sorry for the late response @dmicanzerofox. Postgres surfacer for Cloudprober sounds good to me.

**Comment by manugarg** [comment]
https://github.com/google/cloudprober/commit/25134718bed687e5ebe5fa2d716369aef96489e9 adds the Posgres surfacer.

**Comment by dmicanzerofox** [comment]
Aw yes!! Thank you for all your time @manugarg ! We're going to be able to start using this shortly.  Would you still like the test scripts / documentation?  Should that be part of this issue??

**Comment by manugarg** [comment]
@dmicanzerofox Sounds great. Once you start using it, would you mind sharing how you use cloudprober at https://github.com/google/cloudprober/issues/123.

Adding test scripts / documentation doesn't have to be part of this issue. However, you're probably the right person to add that, so it will be great if you can do that whenever you get a chance.
