### ISSUE TITLE
Add datadog surfacer

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#141]
This should be fairly straightforward. We should probably use:
https://github.com/DataDog/datadog-go

**Comment by manugarg** [comment]
Please let's know if this use is important to you and you'd like to see it implemented sooner.

**Comment by robpickerill** [comment]
Hey Manu, I'd like to also pick this up.

I suspect it will take me a few weeks to implement in between work and other commitments - if you ok with these timeframes? I'll make a start here next week.

**Comment by manugarg** [comment]
Hey @robpickerill,

Sounds good. Thanks for picking it up. :)

**Comment by c6h12o6** [comment]
I accidentally picked this up (without talking to robpickeril, though I am a coworker of his). You can assign it to me if you'd like.

https://github.com/google/cloudprober/pull/594

**Comment by manugarg** [comment]
Closing this as it is done (#594, #627).
