### ISSUE TITLE
Community Grafana Prometheus Dashboard

### ISSUE THREAD

**Issue by dmicanzerofox** [google/cloudprober#142]
While creating grafana dashboards for cloudprober metrics are not very hard, I would personally really enjoy seeing how other people view cloudprobers output.  I was hoping that someone already had a grafana prometheus dashboard that they would be OK with publishing?
Thank you

**Comment by tklovett** [comment]
Ditto on this. It would also be nice to have some community sanity-checking on what to monitor and how to monitor it accurately. I'll start!

### Overview
#### Current Probe State (SingleStat w/ spark line)
```
sum(rate(success{probe=~"$probe"}[1m])) by (probe) / sum(rate(total{probe=~"$probe"}[1m])) by (probe)
```

#### Success Rate
```
sum(rate(success{probe=~"$probe"}[1m])) by (probe) / sum(rate(total{probe=~"$probe"}[1m])) by (probe)
```

### Detailed View
#### Probe Latency (ms)
```
(sum(rate(latency{probe=~"$probe"}[1m])) by (probe)) / (sum(rate(success{probe=~"$probe"}[1m])) by (probe)) / 1000
```

#### Probe Failure Rate (%)
```
((sum(rate(total{probe=~"$probe"}[1m])) by (probe)) - (sum(rate(success{probe=~"$probe"}[1m])) by (probe))) / (sum(rate(total{probe=~"$probe"}[1m])) by (probe))
```

#### Probe Response Status Codes (Stacked %)
```
sum(rate(resp_code{probe=~"$probe"}[1m])) by (probe, code)
```

**Comment by manugarg** [comment]
Filed as https://github.com/cloudprober/cloudprober/issues/24. Please see the announcement at https://github.com/google/cloudprober/discussions/679 for more details.
