### ISSUE TITLE
How to setup a ping probe in cloudprober.cfg

### ISSUE THREAD

**Issue by vivekbny** [google/cloudprober#153]
Hi,
@manugarg 
We are trying to replace the existing BB exporter with cloudprober now. We were able to test the DNS and HTTP probes.
But when we try to test PING probe, it is not working as expected. Can you please assist/tell if something is wrong with my cloudprober.cfg

probe {
   name: "test_ping_job"
   type: PING
   targets {
     gce_targets {
       instances {}
     }
     }
	run_on: "{{"123456.bnymellon.com"}}"
   interval_msec: 12000  # 5s
   timeout_msec: 6000 # 5s
 }

**Comment by manugarg** [comment]
@vivekbny closing this issue due to lack of response. Please feel free to re-open if you're still encountering a problem.
