### ISSUE TITLE
Is em.Clone redundant? 

### ISSUE THREAD

**Issue by MrDragon1122** [google/cloudprober#169]
// Start starts the probe and writes back the data on the provided channel.
// Probe should have been initialized with Init() before calling Start on it.
func (p *Probe) Start(ctx context.Context, dataChan chan *metrics.EventMetrics) {
	if p.conn == nil {
		p.l.Critical("Probe has not been properly initialized yet.")
	}
	defer p.conn.close()
	for ts := range time.Tick(p.opts.Interval) {
		// Don't run another probe if context is canceled already.
		select {
		case <-ctx.Done():
			return
		default:
		}

		p.runProbe()
		p.l.Debugf("%s: Probe finished.", p.name)
		if (p.runCnt % uint64(p.c.GetStatsExportInterval())) != 0 {
			continue
		}
		for _, t := range p.targets {
			em := metrics.NewEventMetrics(ts).
				AddMetric("total", metrics.NewInt(p.sent[t])).
				AddMetric("success", metrics.NewInt(p.received[t])).
				AddMetric("latency", metrics.NewFloat(p.latency[t].Seconds()/p.opts.LatencyUnit.Seconds())).
				AddLabel("ptype", "ping").
				AddLabel("probe", p.name).
				AddLabel("dst", t)

			dataChan <- em.Clone()
			p.l.Info(em.String())
		}
	}
}

For dataChan <- em.Clone(), is this line of code redundant? The operation of the Clone function is to apply for a new memory, for the operation of the memory.

**Comment by MrDragon1122** [comment]
Clone does the new application for a piece of memory and then returns

**Comment by MrDragon1122** [comment]
Thanks for your guidance.
I also found a problem in the test, that is, the data in the Prometheus interface may be stale. If the prometheus database receives older data (such as 7 days ago), it will report an error. Therefore, the time should be added when the interface writes data, and the old data is not sent.


```
	if ps.c.IncludeTimeStamp {
		ps.dataWriter = func(w io.Writer, pm *promMetric, key string) {
			**if promTime(time.Now())-pm.data[key].timestamp < 60*60000 {**
				fmt.Fprintf(w, "%s %s %d\n", key, pm.data[key].value, pm.data[key].timestamp)
			}
		}
	} else {
		ps.dataWriter = func(w io.Writer, pm *promMetric, key string) {
			**if promTime(time.Now())-pm.data[key].timestamp < 60*60000 {**
				fmt.Fprintf(w, "%s %s\n", key, pm.data[key].value)
			}
		}
	}
```

**Comment by manugarg** [comment]
@MrDragon1122 

It's only a non-default option to not specify timestamp in prometheus surfacer. We added that because someone had an issue exporting data because of time-synchronization issues.

Am I understanding your concern correctly?

**Comment by manugarg** [comment]
@MrDragon1122 Can you point me to the prometheus documentation or code that says that it will reject the whole scrape if a metric has a timestamp older than 7d. Or, let me know if I didn't understand the issue clearly.

Also, cloudprober, by itself, re-exports all the relatively unchanging sysvar values, e.g. hostname, environment variables, etc and all the system probes should also keep generating new data unless there is a bug. I was wondering how did you run into a case where data was older than 7 days.

Also, I think we should file another issue for the prometheus surfacer issue.

Thanks in advance.
Manu

**Comment by manugarg** [comment]
Committed https://github.com/google/cloudprober/commit/5d59e2c15807e8471cdbb590f2e899459514ed38 to fix the Clone() issue.

@MrDragon1122 Can you please create a different issue for the prometheus question. I'd do it myself but I think I am not clear about what's the real issue there. Appreciate you looking at it.

Thanks,
Manu
