### ISSUE TITLE
[feature] Prepend a prefix to all metrics

### ISSUE THREAD

**Issue by artherd42** [google/cloudprober#195]
A meaningful prefix, e.g. cloudprober_, would help to distinguish the cloudprober metrics from other metrics. It should be prepended to all stats, automatically.

**Comment by manugarg** [comment]
Is this request specifically for prometheus surfacer? To avoid breaking existing deployments, we can actually make it an option, rather than doing it automatically.

**Comment by tklovett** [comment]
👍 for this request – finding and understanding a metric called `total`, `success`, or `failure` in Prometheus's auto-completion is challenging. This is _especially_ true for new team members who were not involved in getting Cloudprober set up initially.

**Comment by manugarg** [comment]
Feature has been added to the HEAD now. Metrics prefix can be changed by having the following in cloudprober config:

surfacer {
  type: PROMETHEUS

  prometheus_surfacer {
    metrics_prefix: "cloudprober_"
  }
}

**Comment by manugarg** [comment]
Released in v0.10.3.
