### ISSUE TITLE
external prober type for latency with dist metrics.

### ISSUE THREAD

**Issue by Beatrice7** [google/cloudprober#197]
how to for : external prober type for latency with dist metrics and dist timeunit.

**Comment by Beatrice7** [comment]
external_probe: {
    mode: SERVER
    command: ""

    output_metrics_options {
      dist_metric {
        key: "latency"
        value: {
          explicit_buckets: "1000,10000,100000,1000000,2000000,3000000"
        }
      }
    }
  }

for this ?

**Comment by Beatrice7** [comment]
From the metrics output, it is wrong.

**Comment by manugarg** [comment]
@Beatrice7 What is your external probe outputting?

Here is an example config:
https://github.com/google/cloudprober/blob/master/examples/external/cloudprober_aggregate.cfg

that works with the following external prober:
https://github.com/google/cloudprober/blob/master/examples/external/redis_probe.go

Basically external prober outputs strings like this:
set_latency_ms 1.231,1.101,1.006 (comma separated values to build distributions from)
get_latency_ms 1.078,1.103,1.008

Cloudprober collects this output and builds a distribution using the output.

**Comment by Beatrice7** [comment]
but i said the latency metrics is  clouprober build-in metrics.

**Comment by manugarg** [comment]
Sorry, I am not sure I am following you, but I'll try.

If you're using cloudprober's internal metric 'latency', then you have to use different configuration field:
https://github.com/google/cloudprober/blob/daff2753edb47d637a0a60eb49f0931d20774bba/probes/proto/config.proto#L52

It will look something like this:

```
probe {
  type: EXERNAL
  latency_unit: ms
  latency_distribution {
    explicit_buckets: "0.01,0.1,0.15,0.2,0.25,0.35,0.5,0.75,1.0,1.5,2.0,3.0,4.0,5.0,10.0,15.0,20.0,40.0,75.0,100.0"
  }
  
  external_probe {
    mode: SERVER
    command: ..
  }
}
```

Please let me know if that works for you.

**Comment by Beatrice7** [comment]
Thanks for your replied.

but it  can work for type EXERNEL, and only working for type ping.
I have tried it.

**Comment by manugarg** [comment]
@Beatrice7 Can you please share your whole config and error message?


It should work on EXTERNAL probe type too, but for external probe type, your external program should use a metric name other than "latency".

Cloudprober will independently produce a "latency" metric based on how long does server take to respond to the cloudprober request.

**Comment by Beatrice7** [comment]
pls see https://github.com/google/cloudprober/blob/master/probes/external/external.go

// Probe holds aggregate information about all probe runs, per-target.
type Probe struct {
	name    string
	mode    string
	cmdName string
	cmdArgs []string
	opts    *options.Options
	c       *configpb.ProbeConf
	l       *logger.Logger
	ipVer   int

	// book-keeping params
	labelKeys  map[string]bool // Labels for substitution
	requestID  int32
	cmdRunning bool
	cmdStdin   io.Writer
	cmdStdout  io.ReadCloser
	cmdStderr  io.ReadCloser
	replyChan  chan *serverpb.ProbeReply
	success    map[string]int64         // total probe successes
	total      map[string]int64         // total number of probes
	latency    map[string]time.Duration // cumulative probe latency, in microseconds.

	// EventMetrics created from external probe process output
	defaultPayloadMetrics *metrics.EventMetrics
	payloadMetrics        map[string]*metrics.EventMetrics // Per-target metrics
	payloadMetricsMu      sync.Mutex
}

The latency field is time.Duration and it's a cumulative，so it cannot change to distribution metrics.

**Comment by Beatrice7** [comment]
and ple see https://github.com/google/cloudprober/blob/master/probes/ping/ping.go

// Probe implements a ping probe type that sends ICMP ping packets to the targets and reports
// back statistics on packets sent, received and the rtt.
type Probe struct {
	name string
	opts *options.Options
	c    *configpb.ProbeConf
	l    *logger.Logger

	// book-keeping params
	source            string
	ipVer             int
	targets           []string
	sent              map[string]int64
	received          map[string]int64
	latency           map[string]metrics.Value
	validationFailure map[string]*metrics.Map
	conn              icmpConn
	runCnt            uint64
	target2addr       map[string]net.Addr
	ip2target         map[string]string
}

The latency field map[string]metrics.Value, so it can change to distribution metrics.

**Comment by manugarg** [comment]
Ah, you're right. Sorry, I forgot that only HTTP, PING and UDP probes support distributions for latency right now. External probe and DNS probes don't.

It should be easy to fix though. Would you like to send a PR? If not, I can get to it tomorrow.

**Comment by Beatrice7** [comment]
i like it, but I haven't pulled request yet, How do I follow the steps?

**Comment by manugarg** [comment]
Here is the process for contributing to cloudprober:
https://github.com/google/cloudprober/blob/master/CONTRIBUTING.md

For generic PR related information, you'll have to search for "github pull request process" over internet.

However, I have already made a change for this particular issue. I'll commit that tomorrow. But you're welcome to contribute in future. I'd suggest that start with creating a pull request for your own project, to get familiar with the process.

Much thanks for reporting this issue.

**Comment by manugarg** [comment]
@Beatrice7 Sorry about the communication confusion, but In the comment above you had said:
"i like it, but I haven't pulled request yet, How do I follow the steps?"

That's the reason I sent you links about cloudprober's CONTRIBUTING.md and a way to find information about github PR process.

Anyway, I've committed a fix for the issue now. Please feel free to re-open if it still doesn't work for you.

Cheers,
Manu

**Comment by Beatrice7** [comment]
Thank you very much.
