### ISSUE TITLE
github.com/google/cloudprober/cmd:certs has removed, is it not needed?

### ISSUE THREAD

**Issue by Beatrice7** [google/cloudprober#204]
at the github.com/google/cloudprober/cmd/BUILD file， in the past

filegroup(
    name = "certs",
    srcs = [
        "ca-certificates.crt",
    ],
)

but now it has been removed， is it not needed?

**Comment by manugarg** [comment]
@Beatrice7 Wondering where do you see that file? It's from our internal build system (bazel). As far as I remember, we've never exported this file to Github :)

**Comment by Beatrice7** [comment]
In the source code of early 2018

**Comment by Beatrice7** [comment]
package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_docker//docker:docker.bzl", "docker_build")
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_test")

go_binary(
    name = "cloudprober",
    srcs = ["cloudprober.go"],
    deps = [
        "//third-party-go/vendor/cloud.google.com/go/compute/metadata:go_default_library",
        "//third-party-go/vendor/github.com/golang/glog:go_default_library",
        "//third-party-go/vendor/github.com/google/cloudprober:go_default_library",
        "//third-party-go/vendor/github.com/google/cloudprober/config:go_default_library",
        "//third-party-go/vendor/github.com/google/cloudprober/sysvars:go_default_library",
    ],
)

filegroup(
    name = "certs",
    srcs = [
        "ca-certificates.crt",
    ],
)

and file ca-certificates.crt in this folder.

**Comment by Beatrice7** [comment]
ok，thanks，then I don't care.
