### ISSUE TITLE
Partial configuration reload

### ISSUE THREAD

**Issue by AndrzejKasiewicz** [google/cloudprober#206]
Hi,
we are considering usage of Cloudprober in our organization as a part of ErrorBudget tool. We would like to use it to gather metrics from Elastic (numbers of failed/succeeded requests etc.). Second metric source would be active probing services healthchecks. Implementing probe for Elastic shouldn't be a problem. And we can use http probe for healthchecks. But metrics can be changed by users as they add new or change their SLOs. Restarting whole Cloudprober every time metrics change will not work as we would lose too much data. 
Do you think we can use Cloudprober for our use case? Is there any way to change configs only for a part of probes? We considered extending Cloudprober but it seems that we would have to rewrite a lot of code as all probes are using the same context. 

Would #149 solve our problem? Are there plans to add it in foreseeable future?

**Comment by manugarg** [comment]
@AndrzejKasiewicz I am glad to hear that you're considering cloudprober for error budget calculations. 

However, I am curious how will you lose data if cloudprober is restarted. Cloudprober works in conjunction with another monitoring system -- currently supported monitoring systems are  prometheus, stackdriver or PostgresSQL. There are usually bridges available between prometheus and other monitoring systems like AWS Cloudwatch, increasing the number of monitoring systems that cloudprober works with.

If cloudprober is restarted, data is not lost at all as it is stored in a metrics storage system (e.g. prometheus). All the counters will be reset, but that should be safe as the most monitoring systems handle counters resets automatically.

That's how we rollout a new cloudprober config internally -- just restart the cloudprober binary with the new config (we package them together in a docker image).

Regarding #149, it will not help with partial reload. Even if, and when we implement it, we'll be clearing all the state in cloudprober to avoid any sort of data corruption / weird bugs.

Let me know if I didn't understand the problem correctly.

**Comment by AndrzejKasiewicz** [comment]
Hi, thanks for your answer!

Basically we want to scrape logs from Elastic and create metrics based on them in Prometheus. Probe would execute query how many requests succeeded and failed in recent time window. Time window for a probe would move every time it runs. 

So when a cloudprober is restarted we wouldn't know which part of Elastic logs was already scraped and stored in Prometheus. 

Also restarting cloudprober would take a few seconds for which we wouldn't have data from http probe. We are aiming for 1s resolution for healthchecks to monitored services. 

Metrics can be changed dozen of times each hour and we are afraid that restarting cloudprober each time will not work if we want to have accurate data.

**Comment by manugarg** [comment]
Thanks for explaining your use case @AndrzejKasiewicz.

Two things:
1. Restarting cloudprober should ideally take less than a second. For example if you were using docker containers, if you pull the docker image in advance (with docker pull), stopping and starting cloudprober docker image should happen in less than a second. Now, I am not aware if there are certain conditions that make it not so.
2. Regardless though, restarting cloudprober dozens of times each hour also doesn't sound like a good idea. I am not sure what has to change about the metrics, but if you are using an [external probe](https://cloudprober.org/how-to/external-probe/) to create metrics, cloudprober can parse those metrics and create new metrics on the fly (basically your external probe outputs strings like "requests 1566" and cloudprober creates a metric called requests).

Other than that, I think a partial config reload will be very hard to implement cleanly.  We can eventually implement dynamic configuration using gRPC (something like #26), where an external actor configures cloudprober, but that is also a bit far as we haven't even thought about the design yet.

**Comment by manugarg** [comment]
@AndrzejKasiewicz I was wondering what did you decide. Do you think we can close this issue now?

**Comment by AndrzejKasiewicz** [comment]
Hi, for now we decided to use modified version of blackbox exporter. Maybe we will be able to come back to cloudprober someday as its other features would fit well in our setup, but this partial reload issue blocked us from using it.
