### ISSUE TITLE
Jitter to avoid thundering herd?

### ISSUE THREAD

**Issue by MrHohn** [google/cloudprober#212]
Is there any jitter configuration that we can use to avoid large amount of probes going to the same target simultaneously? Context: launching many cloudprober instances at the same time on various locations to probe the same set of targets.

**Comment by manugarg** [comment]
@MrHohn Unfortunately, there is no jitter configuration right now. We usually want probes to run at the specific times, but I can imagine cases where a bit of a jitter will help.

Regarding the thundering herd problem, are all the cloudprober instances being launched simultaneously (curious what's the probe interval)? If it's not possible to stagger the launching of the instances, one of the things that will help is if we introduce a random delay between cloudprober start time and when probe execution loop starts. That will make sure that cloudprober instances are desynchronized, with respect to each other. Do you think that will be sufficient?

**Comment by MrHohn** [comment]
@manugarg Thanks for your inputs. Given an another thought, stagger the launching of the cloudprober instances or even introduce a random delay at startup would be an easy enough option that suffices our use case.

I'm closing this, thanks!
