### ISSUE TITLE
Cannot capture string values

### ISSUE THREAD

**Issue by athul20** [google/cloudprober#231]
Cloudprober is not able to capture the string values outputted by a script while running the script through cloudprober. Cloudprober at the moment can capture numerical values, an enhancement is needed to capture string values.

**Comment by manugarg** [comment]
You'll need to use the latest docker image (instead of the versioned one) to be able to use this feature.

**Comment by athul20** [comment]
Hi Manu,
Thanks for the help.I am just curious to know when will you provide the enhancement in binary version.

**Comment by manugarg** [comment]
I am not planning to cut a new release anytime soon (about 2 months). However building from the source should be straight-forward. From https://cloudprober.org/getting-started:

Assuming that Go is already installed (if not, please follow Go installation process):
```
go get github.com/google/cloudprober
GOBIN=$GOPATH/bin go install $GOPATH/src/github.com/google/cloudprober/cmd/cloudprober.go 
```

If you are using docker, you can simply use the image with the "latest" tag.

**Comment by athul20** [comment]
Thanks Manu. I am using the docker but was not able to run a python script since python is not present in docker image.So is there a way to get that done?
