### ISSUE TITLE
Error download and run the latest docker image

### ISSUE THREAD

**Issue by tweetyss** [google/cloudprober#232]
Hi all, I am a newbie. Help is appreciated. Thanks.

$ docker run --net host cloudprober/cloudprober
I0419 23:19:54.254899       1 cloudprober.go:130] Error reading config from metadata. Err: metadata: GCE metadata "project/attributes/cloudprober_config" not defined
W0419 23:19:54.255019       1 cloudprober.go:139] Config file /etc/cloudprober.cfg not found. Using default config.
I0419 23:19:54.306354       1 sysvars_gce.go:63] No instance_template found. Defaulting to undefined.
F0419 23:19:54.316272       1 cloudprober.go:178] Error initializing cloudprober. Err: error while creating listener for default HTTP server. Err: listen tcp :9313: bind: addr
ess already in use

**Comment by manugarg** [comment]
Looks like something is already listening on port 9313. It's possible it's another instance of cloudprober; you can verify that by going to http://localhost:9313/status.

In any case, you can change cloudprober listening port by setting the environment variable CLOUDPROBER_PORT before running the docker command:

$ export CLOUDPROBER_PORT=9314

**Comment by manugarg** [comment]
Closing as this is not really a cloudprober issue. It's a port conflict issue that can be resolved by the suggestion above.

**Comment by tweetyss** [comment]
I already tried "export CLOUDPROBER_PORT=9314" and do the "docker run" command again but still see the same error:

F0422 17:34:59.838048       1 cloudprober.go:178] Error initializing cloudprober. Err: error while creating listene
r for default HTTP server. Err: listen tcp :9313: bind: address already in use

**Comment by tweetyss** [comment]
$ curl  http://localhost:9313/status 

...
<b>Started</b>: Fri, 19 Apr 2019 23:09:02 UTC -- up 66h29m10.909013325s<br/>
<b>Version</b>: <br>
<b>Config</b>: <a href="/config">/config</a><br>
<h3>Probes:</h3>
<table class="status-list">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Interval</th>
    <th>Timeout</th>
    <th width="20%">Targets</th>
    <th width="30%">Probe Conf</th>
    <th>Latency Unit</th>
    <th>Latency Distribution Lower Bounds (if configured) </th>
  </tr>
  
</table>
<h3>Surfacers:</h3>
<table class="status-list">
  <tr>
    <th>Type</th>
    <th>Name</th>
    <th>Conf</th>
  </tr>
  
  <tr>
    <td>PROMETHEUS</td>
    <td></td>
    <td>
    
      <pre>&lt;nil&gt;</pre>
    
    </td>
  </tr>
  
  <tr>
    <td>FILE</td>
    <td></td>
    <td>
    
      <pre>&lt;nil&gt;</pre>
    
    </td>
  </tr>
  
</table>
<h3>Servers:</h3>
<table class="status-list">
  <tr>
    <th>Type</th>
    <th>Conf</th>
  </tr>
  
</table>

**Comment by tweetyss** [comment]
Looks like what you said, another instance of cloudprober has run (how? I don't know) with an empty config. Is there a way to stop it?

**Comment by manugarg** [comment]
@tweetyss I suggest that you search for "how to stop a process" or how to stop a docker container.
