### ISSUE TITLE
Http probe does not read system variable for http/s_proxy settings or provide a way to specify network proxy details 

### ISSUE THREAD

**Issue by faiyazshk** [google/cloudprober#233]
Tried the example on cloudprober.org calling google.com but it failed as in my network I can only make external calls via network http proxy settings but the system proxy settings are ignored and also there is no way to specify proxy url and port in the probe configuration.

**Comment by manugarg** [comment]
Fixed by the commit: f1878a9f795b6f78630eabca246a1588659532d5. Environment variables should work now.
