### ISSUE TITLE
Add gRPC service to dynamically configure Cloudprober

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#246]
Cloudprober should provide a gRPC service that can be used to configure cloudprober dynamically and remotely. 

To be begin with, service should allow only adding and removing probes. We can later on think about allowing editing existing probes. Adding and removing probes must be much easier than editing existing probes.

**Comment by manugarg** [comment]
Look at #26 for similar but slightly different issue.

**Comment by manugarg** [comment]
PR https://github.com/google/cloudprober/pull/250 adds this support.

**Comment by manugarg** [comment]
First pass of the service has been added and released as part v0.10.3.

**Comment by sairohith** [comment]
Hi, can you explain how to use the gRPC service by cloudprober, may be a documentation with an example helps a lot. Also, I have a doubt will the adding of new probe actually creates a new instance of cloudprober as I saw in client.go its trying to run at port 9314, so I thought I have to look into localhost:9314/status for the added probe?
Could you help me out with this?
