### ISSUE TITLE
Extend HTTP probe type to add support for OAuth-authenticated probes

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#27]

**Comment by p-singh** [comment]
@manugarg I would like to contribute to this feature. Could you let me know what initial ideas you have in mind and some pointers to start and I shall take it up from there?

**Comment by manugarg** [comment]
@p-singh That's great. I actually didn't give much thought to the implementation, but thinking about it now, it seems like main challenge is going to be abstracting out various credential formats. I am most familiar with Google style credentials and for those, first step could simply be supporting Application Default Credentials:
https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application

What use case did you have in mind for this feature. Understanding that could be useful in planning this further.

**Comment by manugarg** [comment]
Wrote some ideas here:
https://gist.github.com/manugarg/1726dfbbc312c0a074d592140dae9aee

**Comment by manugarg** [comment]
Assigning to myself as I have started working on it.

**Comment by manugarg** [comment]
https://github.com/google/cloudprober/commit/2410e7e1d918e2694e660e07d7417460bba0a49b added OAuth support for HTTP probe.

**Comment by manugarg** [comment]
Support for JWT as web token: https://github.com/google/cloudprober/commit/0ee300c3e03f4df88eb7c98fcb30d3cb4c4cf689

Next up, I'll be adding support for reading JSON key file (and other files) from GCS.

**Comment by manugarg** [comment]
This is now available in the v0.10.7 release:
https://github.com/google/cloudprober/releases/tag/v0.10.7
