### ISSUE TITLE
[feature] to support API call with go client pkg

### ISSUE THREAD

**Issue by chinglinwen** [google/cloudprober#271]
This is a feature request.

to support update config by API, rather than change config and do restart.

I expect a service that support API call, which I can use Golang client package to do the call, to update/add/delete ( probe item ), may also update local config file at the same time( so latest config survival process restart ).

**Comment by chinglinwen** [comment]
As the new release v0.10.4,  Cloudprobe support Dynamic configuration via gRPC service.

by reading this code https://sourcegraph.com/github.com/google/cloudprober/-/blob/prober/prober.go#L86:19

I think Cloudprobe doesn't support persistent for now?

**Comment by manugarg** [comment]
@chinglinwen That's correct. Cloudprober doesn't persist config changes. It becomes really tricky to do both -- dynamic reconfiguration as well as persistence. We can probably do something along the lines of checkpointing, but maintaining and cleaning up checkpoints is also tricky.

Currently the expectation is that the client software will maintain the config and will recreate (if cloudprober dies for some reason) cloudprober with the latest config.
