### ISSUE TITLE
time.Tick leaks

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/cloudprober#275]
https://github.com/google/cloudprober/blob/6eeacca62dd2bfbd07611b7e5ca31708005039de/probes/dns/dns.go#L248
Leaks when `return`:
https://github.com/google/cloudprober/blob/6eeacca62dd2bfbd07611b7e5ca31708005039de/probes/dns/dns.go#L252

https://golang.org/pkg/time/#Tick

**Comment by manugarg** [comment]
Thanks @QiAnXinCodeSafe. With gRPC service to add/remove probes, ticker leaks really became important. Fixed in the commit referenced above.
