### ISSUE TITLE
Add support for AWS environment meta data

### ISSUE THREAD

**Issue by kirk-daries** [google/cloudprober#294]
Currently, the only cloud platform exposing any metadata is GCE via:
https://github.com/google/cloudprober/blob/master/sysvars/sysvars_gce.go

It would be nice to expose AWS meta data when the probes are run on Amazon EC2's, such as REGION, etc

**Comment by kohend** [comment]
#315 Made a PR for this

**Comment by manugarg** [comment]
Marking closed. To track the release of this feature, please look at https://github.com/google/cloudprober/issues/326.
