### ISSUE TITLE
[HTTP probe] Add capability to run multiple parallel probes per cycle

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#319]
HTTP probe enhancement:

Add capability to run multiple parallel probes per cycle. This is useful if someone wants to run a lot of HTTP probes against a target without increasing prober footprint.

CC: @ls692

**Comment by aidarbek** [comment]
Do I understand it correctly that we need to execute this loop concurrently (with goroutines)? https://github.com/google/cloudprober/blob/c153aa4e8ce7e51de653ddfb6888710e126690e6/probes/http/http.go#L311
Also, should it be optional (by specifying command line argument), as DNS probe runs in parallel by default?https://github.com/google/cloudprober/blob/c153aa4e8ce7e51de653ddfb6888710e126690e6/probes/dns/dns.go#L205

**Comment by manugarg** [comment]
@aidarbek Yeah, something like that. I hacked up something last night. I'll send you a CL? :)

(Sorry, should have assigned it to myself before working on it.)

**Comment by manugarg** [comment]
Marking closed. To track the release of this feature, please look at https://github.com/google/cloudprober/issues/326.
