### ISSUE TITLE
Make cloud logging optional

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#322]
Cloudprober logs to stackdriver if running on GCE. There should be an option to disable it.

**Comment by asheikm** [comment]
Hi , do you mind if i take it ? and any estimate on release plan for this issue fixed ?

**Comment by manugarg** [comment]
Thanks for the offer @asheikm. Someone already sent me a change for this. It's getting delayed by my vacation right now. I am away from work until Nov 29.

**Comment by asheikm** [comment]
ok , Please let me know any other issue or enhancement i can contribute ?
