### ISSUE TITLE
Will this support the new k8s Pod ready++ feature?

### ISSUE THREAD

**Issue by renier** [google/cloudprober#337]
It would be great if this could update additional pod readiness states based on thresholds using the new [Pod ready++](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0007-pod-ready%2B%2B.md) feature.

**Comment by manugarg** [comment]
@renier ah, you mean using cloudprober probe status as a readiness condition? I could not figure that out from ready++ document linked above. For example, the API to update the pod condition is not clear to me.

**Comment by renier** [comment]
@manugarg Found this https://godoc.org/github.com/ericchiang/k8s/apis/core/v1#PodReadinessGate

**Comment by manugarg** [comment]
Moved here: https://github.com/cloudprober/cloudprober/issues/28. Please see the announcement here for the background: https://github.com/google/cloudprober/discussions/679.
