### ISSUE TITLE
[Help] How to use Probe specific Configs?

### ISSUE THREAD

**Issue by Daxten** [google/cloudprober#35]
In the docs only the code is linked, and since I'm not familiar with protobuff / go it didn't really help me.. my naiv approach was sth like this:

```
probe {
  name: "cloudprober"
  type: HTTP
  targets {
    host_names: "google.de"
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
  relative_url: "/"
}
```

but that already doesnt work, the config files also don't have a property for sth like "AbstractSpecialProbeConfig" and / or there is no inheritance, so where should I put the property? (maybe sth. for the docs?)

also adding more then 1 HTTP Probe only worked via host_names: "host1.de, host2.de" which was also not very clear for me (I guess it only matches against the first probe of a type it finds?)

**Comment by manugarg** [comment]
Hello Daxten,

Following will be the correct config:

probe {
  name: "cloudprober"
  type: HTTP
  targets {
    host_names: "google.de"
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
  http_probe {
    relative_url: "/"
  }
}

Following test config may help a bit:
https://github.com/google/cloudprober/blob/master/cmd/cloudprober_test.cfg

I am planning to add some examples and documentation soon.

**Comment by Daxten** [comment]
Cool thanks that helped! 👍
