### ISSUE TITLE
[Documentation] Adding multipart form data to a request body

### ISSUE THREAD

**Issue by nvidyala** [google/cloudprober#381]
Hi,

I wasn't able to find any examples within the repo for making a POST request with a multipart/form-data body. Is it possible to do this through the configuration file itself or would I have to create an external probe?

Thanks in advance

**Comment by manugarg** [comment]
@nvidyala Sorry for not responding earlier. It's not possible to do this through config files as of now.

Also, please see the announcement here: https://github.com/google/cloudprober/discussions/679. We are archiving this repository. If you're still interested in this, can you please find a feature request here: https://github.com/cloudprober/cloudprober/issues.
