### ISSUE TITLE
[Bug] Kubernetes service discovery does not discover ports

### ISSUE THREAD

**Issue by networkop** [google/cloudprober#420]
**What happened:** When using k8s service discovery to discover services, ports do not get discovered.

**What you expected to happen:** pb.Resource for the discovered k8s service to contain `svc.Spec.Ports[0].Port`

**How to reproduce it (as minimally and precisely as possible):** create a k8s cluster and use k8s discovery to discover a service. the returned *pb.Resource has an empty `Port`

**Anything else we need to know?:** it looks like ports are not set for k8s services at all, not sure if this is intentional or not. There's also an issue with services potentially containing multiple ports and pb.Resource only has a single Port field. Perhaps iterating over ports and creating a new pb.Resource for each unique one could be the right solution?

**Comment by manugarg** [comment]
@networkop Thanks for reporting this.

Your assessment is right about services discovery not populating the port. This seems like an oversight. For multiple ports case, I think we need to handle multiple ports the same way as endpoints:
https://github.com/google/cloudprober/blob/f668a7f5530241c1b3186905a151908157f75059/rds/kubernetes/endpoints.go#L87

**Comment by manugarg** [comment]
I'm working on a change for this.

**Comment by manugarg** [comment]
Closing this now. Filed a separate bug for the next release: v0.10.8.
