### ISSUE TITLE
Add a way to specify HTTP "Host" header based on targets

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#438]
@JohnWillker wrote in #437.

There's another problem here. If the service is in a different namespace from the `default`, the Host header is sent incomplete.

I don't know, maybe something here?
https://github.com/google/cloudprober/blob/dd0bb3e2e8a54038da64c9b092db2f8941ecb69c/probes/http/request.go#L54

Is sent only the `service` name(i think).

If you are using Istio this not work, you need to pass the entire [FQDN](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) like: `service.namespace.svc.cluster.local`

Because this cause `upstream connect error`

Look:

Without FQDN:

```shell
root@debug:/# curl  http://10.4.15.152:8800/healthz -v -H "Host:payout-http"
*   Trying 10.4.15.152...
* TCP_NODELAY set
* Connected to 10.4.15.152 (10.4.15.152) port 8800 (#0)
> GET /healthz HTTP/1.1
> Host:payout-http
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Wed, 05 Aug 2020 15:57:19 GMT
< server: envoy
<
* Connection #0 to host 10.4.15.152 left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

With FQDN:

```shell
root@debug:/# curl  http://10.4.15.152:8800/healthz -v -H "Host:payout-http.example-prod.svc.cluster.local"
*   Trying 10.4.15.152...
* TCP_NODELAY set
* Connected to 10.4.15.152 (10.4.15.152) port 8800 (#0)
> GET /healthz HTTP/1.1
> Host:payout-http.example-prod.svc.cluster.local
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 204 No Content
< date: Wed, 05 Aug 2020 15:57:58 GMT
< x-envoy-upstream-service-time: 6
< server: envoy
<
* Connection #0 to host 10.4.15.152 left intact
```

Are causing problems in all targets.
```logs
I0805 14:35:45.535230       1 http.go:258] Target:payout-http:8800, URL:http://10.4.15.152:8800/healthz, response: upstream connect error or disconnect/reset before headers. reset reason: connection termination
I0805 14:35:45.535516       1 http.go:258] Target:risk-evaluator:5000, URL:http://10.4.0.38:5000/healthz, response: upstream connect error or disconnect/reset before headers. reset reason: connection termination
I0805 14:35:45.535792       1 http.go:258] Target:validation-app:80, URL:http://10.4.15.88:80/healthz, response: upstream connect error or disconnect/reset before headers. reset reason: connection termination
I0805 14:35:45.535969       1 http.go:258] Target:payout-http:8800, URL:http://10.4.15.152:8800/healthz, response: upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

**Comment by manugarg** [comment]
It seems we need a way to specify host headers based on targets, for example, we should be able to add something like the following in probe config:

```
header {
  name: "Host",
  value:  "@target.name@. @target.label.namespace@.svc.cluster.local"
}
```

**Comment by manugarg** [comment]
@JohnWillker,

https://github.com/google/cloudprober/pull/444 implements a change that will allow you to specify target based host headers using a target label - "fqdn".

Can you add "fqdn" label to the service that you're creating in Kubernetes?

**Comment by JohnWillker** [comment]
> @JohnWillker,
> 
> #444 implements a change that will allow you to specify target based host headers using a target label - "fqdn".
> 
> Can you add "fqdn" label to the service that you're creating in Kubernetes?

@manugarg Perfectly, now everything is working as expected. I'm using the "fqdn" label and solve the connections problems. 
Thank you again.

**Comment by manugarg** [comment]
Excellent. Thanks again for reporting this and the other issue.
