### ISSUE TITLE
Cloudprober returning target without correct host for external probe

### ISSUE THREAD

**Issue by JohnWillker** [google/cloudprober#451]
I have config an external probe to can perform probes in gRPC service.

```yaml
probe {
      type: EXTERNAL
      name: "grpc-internal-probe"
      targets {
        rds_targets {
          resource_path: "k8s://services"
          filter {
            key: "labels.probetype"
            value: "grpc"
          }
          filter {
            key: "labels.fqdn"
            value: ".*.svc.cluster.local"
          }
        }
      }
      external_probe {
        command: "/bin/grpc_health_probe -addr=@target@:50051"
      }
      interval_msec: 10000
      timeout_msec: 5000
    }

rds_server {
      provider {
        kubernetes_config {
          services {}
        }
      }
    }
```

I have a Cloudprober custom docker image with the this [tool](https://github.com/grpc-ecosystem/grpc-health-probe)
So i can perform this: `command: "/bin/grpc_health_probe -addr=@target@:50051"`

But in my clusters, all services serve behind the istio-proxy.
So we have the same problem related here: https://github.com/google/cloudprober/issues/438

The `@target@` come only with the name of the service like `my-app`, but to work in Istio we need the FQDN of the service like `my-app.my-namespace.svc.cluster.local`.

See the error:
```logs
I0828 14:48:16.646542       1 external.go:510] Running external command: /bin/grpc_health_probe -addr=my-app:50051
E0828 14:48:17.653696       1 external.go:519] external probe process died with the status: exit status 2. Stderr: timeout: failed to connect service "my-app:50051" within 1s
```

There some way to deal with this?

**Comment by manugarg** [comment]
I guess we can provide a way to access target labels on the command line the same way as @target@, for example @target.label.fqdn@. I'll take a stab at it

**Comment by manugarg** [comment]
#454 adds the way to access target's fqdn using "@target.label.fqdn@" in command arguments. Can you please give that a try and let me know if it's not working.

**Comment by JohnWillker** [comment]
> #454 adds the way to access target's fqdn using "@target.label.fqdn@" in command arguments. Can you please give that a try and let me know if it's not working.

This work perfectly, thank you again for the fast resolution 👍
