### ISSUE TITLE
External probe command arguments not always parsed properly

### ISSUE THREAD

**Issue by sunshinekitty** [google/cloudprober#473]
https://github.com/google/cloudprober/blob/03e73285d2919eaf102c8ff310c9978db96c5e01/probes/external/external.go#L141

With commands that contain quoted strings with spaces this logic fails.

Eg `./command --flag one --otherflag "two three"` becomes `['--flag', 'one', '--otherflag' '"two' 'three"']` instead of `['--flag', 'one', '--otherflag', '"two three"']`

Using a lexer like https://github.com/google/shlex can add support for these use cases.

**Comment by manugarg** [comment]
@sunshinekitty Thanks for the filing the bug and the suggestion to use shlex.

Yes, we use very basic command parsing today. I'll look at improving it.

**Comment by manugarg** [comment]
I verified that shlex will work fine for our use case. I'll submit a fix soon.

**Comment by sunshinekitty** [comment]
Thanks! Just wanted to report back I've pushed out a build with this change and parsing works as I'd expect.
