### ISSUE TITLE
OAuth2 with Google Credentials and ServiceAccount key doesn't support id_token

### ISSUE THREAD

**Issue by ali-sattari** [google/cloudprober#480]
**Describe the bug**
When trying to use oAuth in an HTTP probe with a ServiceAccount JSON key file against a [GCP IAP](https://cloud.google.com/iap) protected service, auth fails with the content of Google login page in the response body (logged by setting `-debug_log` flag).

This is the config:
```
probe {
  name: "probe-with-oauth"
  type: HTTP
  interval_msec: 5000
  targets {
    host_names: "iap-protected.example.com"
  }
  http_probe {
    protocol: HTTPS
    relative_url: "/some/path/"
    oauth_config {
      google_credentials{
        json_file: "/etc/cloudprober/gcp-sa-key.json"
        scope: "xxxx-yyyyyyyyy.apps.googleusercontent.com"
      }
    }
  }
  validator {
    name: "check_result"
    regex: "some_expected_string"
  }
}
```

**Cloudprober Version**
`v.0.11.0`

**To Reproduce**
1. Config a probe against an IAP protected service, provide SA key file and proper ClientID and `scope`
2. Set validator that fits your service (since the response is an `HTTP 200` from IAP with login page as content)
3. Run Cloudprober with given config and check metrics for success and validation fails

**Comment by manugarg** [comment]
Thanks for reporting this (and the fix PR), @ali-sattari. I added a comment to your PR.

**Comment by manugarg** [comment]
Fixed through: https://github.com/google/cloudprober/commit/f40ed7edb0fe88142a55b0e968b623bb9a8be92b.
