### ISSUE TITLE
Provide an option to disable sysvars logging

### ISSUE THREAD

**Issue by javiergp** [google/cloudprober#493]
Currently sysvars are always reporting and it has impact in the surfacer (i.e. storage in Stackdriver). In our use case we only need to report the latency so it would be great to have a way to disable the report of the rest of metrics.

**Comment by manugarg** [comment]
Hello @javiergp, I just realized there is an option to limit the variables exported to stackdriver:
https://github.com/google/cloudprober/blob/b7a37672cc92137c9858af0cd126df931ab9aad3/surfacers/stackdriver/proto/config.proto#L21

I think that will meet your requirement. Can you please verify?

**Comment by javiergp** [comment]
Thank you @manugarg it works for Cloud Monitoring metric! However it still logs to Cloud Logging but that's not an issue right now.

**Comment by manugarg** [comment]
Cool. Renamed the issue to say "provide an option to disable sysvars logging".

**Comment by manugarg** [comment]
I just verified that sysvars logs to cloud logging only in the beginning:
https://github.com/google/cloudprober/blob/34627fb79d281b4236c7f21f1eec2ba785c5a773/sysvars/sysvars.go#L185

or, if debug mode is enabled.

I am going to close it now. Please feel free to re-open if it's still an issue.
