### ISSUE TITLE
Possibility to configure latency prober as GAUGE

### ISSUE THREAD

**Issue by javiergp** [google/cloudprober#494]
Currently Latency prober is a CUMULATIVE metric (or it can be configured as distribution). This is useful for high frequency probing, however there are more simple use cases that only require to monitor an onprem to cloud connectivity so a metric non-cumulative would be enough and simpler to configure in Cloud Monitoring (stackdriver)

**Comment by benner** [comment]
This also can be helpful if surfacer is PostgreSQL (not need to us window functions like LAG() or LEAD())

**Comment by manugarg** [comment]
Testing a way to do this for stackdriver surfacer in https://github.com/google/cloudprober/tree/sd_gauge

**Comment by manugarg** [comment]
#604 should solve this. You can simply add "export_as_gauge" to any surfacer config and surfacer will export metrics as gauge metrics.

**Comment by manugarg** [comment]
Closing this as it is done now.
