### ISSUE TITLE
[Documentation] Add docs for surfacers

### ISSUE THREAD

**Issue by icco** [google/cloudprober#497]
Add examples and more information about how to use different types of surfacers in the online docs. It's unclear how to send data to Stackdriver for example.

**Comment by manugarg** [comment]
Thanks for filing this, @icco (Hello, by the way :)). I am working on the documentation for Stackdriver as this has come up quite a few times recently. 

In the meantime, the smallest config for stackdriver looks like the following:

```
surfacer {
  type: STACKDRIVER
}
```

You can have multiple surfacers, for example, to add both, prometheus and stackdriver surfacer:

```
surfacer {
  type: PROMETHEUS
}

surfacer {
  type: STACKDRIVER
}
```

More config options:

https://github.com/google/cloudprober/blob/master/surfacers/stackdriver/proto/config.proto
https://github.com/google/cloudprober/blob/master/surfacers/prometheus/proto/config.proto

**Comment by icco** [comment]
👋 ! neat, thanks! Talking a bit about how wonderful cloudprober is in a book for https://newline.co so just want to make sure that if I send folks here they have all of the docs they need to be successful.

**Comment by manugarg** [comment]
That's great. Thanks Nat! :)

Added some initial documentation on surfacers:
https://cloudprober.org/surfacers/overview/
https://cloudprober.org/surfacers/stackdriver/

I'll add some examples as well.

**Comment by manugarg** [comment]
Added examples here: https://github.com/google/cloudprober/tree/master/examples/surfacers (commit: https://github.com/google/cloudprober/commit/4be46a994f2ba47b4f71a227f3db47297ce275c3).

**Comment by manugarg** [comment]
Closing the bug now. I'll look forward to reading your book, @icco :)
