### ISSUE TITLE
Expose pprof as endpoint

### ISSUE THREAD

**Issue by ltagliamonte-dd** [google/cloudprober#522]
**Describe the feature you'd like and the problem it will solve**
The current pprof metrics are exposed on disk and this is not great for debugging in a container environment.
Would be possible to expose those metrics as http endpoints, like:
```
	http.HandleFunc("/debug/pprof/", pprof.Index)
	http.HandleFunc("/debug/pprof/cmdline", pprof.Cmdline)
	http.HandleFunc("/debug/pprof/profile", pprof.Profile)
	http.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
	http.HandleFunc("/debug/pprof/trace", pprof.Trace)
```
I'm ceasing down a tiny mem leak that after extensive tests I belive it is not related to my custom probe and having pprof endpoint exposed as HTTP endpoint would make my troubleshooting way easier.
Thanks!!

**Comment by manugarg** [comment]
pprof is already available at these URLs. 

http://<cloudprober-host>:9313/debug/pprof and other URLs should work.

**Comment by ltagliamonte-dd** [comment]
thank you for the quick reply!!
