### ISSUE TITLE
Previously working k8s probe workers are crash looping

### ISSUE THREAD

**Issue by greglaun-google** [google/cloudprober#543]
**Describe the bug**

I am running some probes on Kubernetes following the guidance on https://cloudprober.org/. They began crash looping on Dec 10.

The proximate cause is that runProbe calls req.WithContext without checking whether req is nil https://github.com/google/cloudprober/blob/34627fb79d281b4236c7f21f1eec2ba785c5a773/probes/http/http.go#L336 This causes a segmentation violation.

The issue was introduced in PR #521.

A related issue is that I was using the latest Cloudprober Docker container, and that caused me to run unreleased code. See "Additional Context" below.

**Cloudprober Version** 

unreleased

**To Reproduce**

I can send the actual config file if you message me directly, but I'm able to produce a nil request with this slight modification of the config in the documentation. 

> cat > /tmp/cloudprober.cfg <<EOF
probe {
  name: "google_homepage"
  type: HTTP
  targets {
    host_names: "https://www.google.com" # Note the https
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
}
EOF

> cloudprober --config_file /tmp/cloudprober.cfg

**Additional context**
I followed the cloudprober.org suggestion to use the latest Cloudprober Docker container. Since this was on the official page, I assumed that the :latest tag tracked the latest official release.

However, a container was pushed 8 days ago on [Docker Hub](https://hub.docker.com/r/cloudprober/cloudprober/tags?page=1&ordering=last_updated) with code that isn't associated with any release tag. You may want to clarify in the documentation whether :latest is intended to track development or whether it's intended to track releases.

**Comment by manugarg** [comment]
Thanks a lot for filing this issue @greglaun-google. This is very helpful.

IIUIC, it's getting triggered by invalid host names. Where earlier cloudprober will simply ignore if there is an error in creating requests, now it crashes because we are not checking for nil requests. We need to fix this ASAP.

Other than that, this issue highlights a bunch of other possible improvements:
* We need to verify `targets.host_names` when we create probes. We'll be able to provide better error message at that time.
* We'll also add more tests for HTTP probe code (we have quite a few tests but we always provide correct targets for testing).

Regarding docker versions:
I agree that the current behavior of "latest" is probably not appropriate. Currently latest is built from the HEAD of the master branch. I think the right behavior here will be to point "latest" to the latest release, instead of pointing it to the latest build docker image.

I am planning to change tags in the following manner:

| Tag | Built from|
|--------|---------------|
| master  | HEAD of the master branch. |
| latest    | Latest tagged release. |
| v0.11.1. | Release v0.11.1. |

**Comment by manugarg** [comment]
Just wanted to update that docker tag changes mentioned above have been implemented. "latest" is now pointing to the last release.

**Comment by greglaun-google** [comment]
Awesome thanks for the update and for responding so quickly! I'm not sure the issue I was facing with my real config was caused by a bad host name. I'll send it to you outside this bug so you can take a look.

**Comment by manugarg** [comment]
It's the "https://" in the targets field that fails the request creation. It should have only hostname in it.

> targets {
host_names: "https://www.google.com" # Note the https
}

**Comment by greglaun-google** [comment]
I was able to create a minimal example based on the problem with my config. The issue is the presence of a custom HTTP verb, which [Google indicates by appending the verb to the URL after a colon.](https://cloud.google.com/apis/design/custom_methods#http_mapping).

This issue appears to have been introduced in PR #505. The issue is likely the line https://github.com/google/cloudprober/blob/f16a0a0419916fb40a0198e9281d10cec751efff/probes/http/request.go#L118
which appears to treat a host as a literal IPv6 address if it contains a colon.

Here's the config to reproduce:

```
probe {
  name: "google_homepage"
  type: HTTP
  targets {
    host_names: "www.google.com/foo:customVerb"
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
}
```

**Comment by greglaun-google** [comment]
In Logs Explorer, I'm seeing logs that say

`target: www.google.com/foo:customVerb, error creating HTTP request: parse http://[www.google.com/foo:customVerb]: missing ']' in host `

**Comment by manugarg** [comment]
That's correct. We started doing things assuming that a host is actually a host.

For HTTP probe, verb and URLs should be configured in the http_probe{} stanza. It's a mistake on cloudprober's part that error message is not clear. Quoting my previous comment:

> We need to verify targets.host_names when we create probes. We'll be able to provide better error message at that time.

We need to verify that "targets.host_names" contains only host names .. i.e. no port, no URL, no protocol, etc. I'll do that soonish.

**Comment by greglaun-google** [comment]
Ok thanks! So host_names should really truly be a comma separated list of actual host names.

I can confirm that moving the URL to the relative_url field of http_probe works.

One of the things that confused me is that the following config is still valid on master, but IIUC, this will soon be rejected by rules that validate the host name:

```
probe {
  name: "google_homepage"
  type: HTTP
  targets {
    host_names: "www.google.com/foo"  # path with no colon is currently OK, but should be rejected IIUC.
  }
  interval_msec: 5000  # 5s                                                                                                                                                                                                                                                                  
  timeout_msec: 1000   # 1s                                                                                                                                                                                                                                                                  
}
```
