### ISSUE TITLE
Have the ability to override configuration targets with a flag.

### ISSUE THREAD

**Issue by skalle** [google/cloudprober#557]
What we're trying to do: 

- Spin up cloudprobers during Spinnaker deployments. Targets should be the base and canary versions, they're not know until Spinnaker has executed it's Deploy step.
- Use the resulting metrics as part of the Spinnaker CAS run. 

We use external probers that are packaged together with cloudprober in Docker images.
The prober configuration lives in the same repo and is packaged along with cloudprober in the image. 

If cloudprober had a `targets` flag to override probe targets it'd be easy to just patch the deploy manifest.
Or maybe a way to just override labels with flags.

The "right" way might be to have the configs go to k8s configMaps but looks like that'd be a fair bit more complex in our case.

**Comment by skalle** [comment]
Ended up doing this with configMaps in the end.

**Comment by manugarg** [comment]
Cool. Glad that it worked out for you, @skalle.

Another option you have is to use file-based targets. It's not documented very well, but following proto file may help:
https://github.com/google/cloudprober/blob/master/targets/file/proto/config.proto

**Comment by skalle** [comment]
Hey @manugarg , that option would have been optimal. 

From what I can see though it's only possible to configure RDS targets.
