### ISSUE TITLE
Need few explanation on cloudprober

### ISSUE THREAD

**Issue by vivekbny** [google/cloudprober#58]
Hi,

I see a metric named **latency**. just wanted to know if that latency metric is actually - latency of the cloudprober or from the network.

Also after adding/updating the URL in the cloudprober.cfg, is there anyway to reload it on the run-time. Every-time after making the changes in the file, i am re-starting the container.

Can someone advise ?

Thanks

**Comment by xbblq7n** [comment]
Can someone help ?

**Comment by vivekbny** [comment]
please address on the above query?

**Comment by manugarg** [comment]
@vivekbny I am going to assume that I answered you question and close the issue :) Feel free to reopen if that's not the case.

**Comment by vivekbny** [comment]
Thanks @manugarg
