### ISSUE TITLE
GKE Auto detection for metric labeling

### ISSUE THREAD

**Issue by guilledipa** [google/cloudprober#580]
When running on GKE, it would be great to have automatic labeling for the metrics, similarly to how it is done for GCE.

It would be useful if on GKE we can set the resource to k8s_cluster/ k8s_node / k8s_pod / k8s_container.

Additionally, some attributes are worth having as resource labels: project_id, cluster_name, location, pod_name, node_name, namespace_name, container_name (e.g use case: multi-tenant clusters).

As reference, the resource labels for the GKE `K8sContainer` schema is defined as:

* `project`: Immutable project number (gaia id) that uniquely identifies the project to which this container belongs.
* `location`: The location (e.g. GCE zone or region) of the GKE cluster in which the container is located. It is immutable for the life of a container.
* `cluster_name`: Immutable name of the cluster that the container is running in. The combination of project+location+cluster represent a globally (but not temporally) unique identifier for a cluster.
* `namespace`: Immutable name of the namespace that the container is running in.
* `pod_name`: Immutable name of the pod that the container is running in.
* `container_name`: Immutable name of the container.

**Comment by guilledipa** [comment]
Similar to this `enhancement`; logging is also by default going to `resource.type="gce_instance"` which isn't ideal when running on GKE.

**Comment by manugarg** [comment]
#622 should fix the logging issue for GKE.

**Comment by manugarg** [comment]
Note that to access container_name, you'll need to set CONTAINER_NAME environment variable in your deployment config.
