### ISSUE TITLE
Improve regex filtering in surfacers

### ISSUE THREAD

**Issue by robpickerill** [google/cloudprober#590]
From: https://github.com/google/cloudprober/pull/583 / https://github.com/google/cloudprober/pull/583#discussion_r615179757

```
 I think we'll need to have something more generic, something like
map<string, string> allowed_metrics
map<string, string> ignore_metrics
where key is the label key, and value is a regex.
```

Moving this comment to an issue so that its not lost in the PR.

**Comment by manugarg** [comment]
Thanks for capturing it here, @robpickerill.

I'll soon submit a change for this.

**Comment by manugarg** [comment]
#597 should fix this.

**Comment by robpickerill** [comment]
Thanks Manu, I started on this PR to update the docs to help out: https://github.com/google/cloudprober/pull/598

**Comment by manugarg** [comment]
Closing this. Release will be tracked through the milestone v0.11.3.
