### ISSUE TITLE
Running On Kubernetes pod encounter an error on OpenStack

### ISSUE THREAD

**Issue by lklkxcxc** [google/cloudprober#592]
**Describe the bug**
Deploy CloudProber on Kubernetes, POD error after startup:
```
F0425 08:05:06.270397       1 cloudprober.go:182] Error initializing cloudprober. Err: sysvars_ec2: could not get instance identity document EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: EC2MetadataError: failed to make EC2Metadata request
        status code: 404, request id: 
caused by: 404 Not Found

The resource could not be found.
```

**Cloudprober Version**
master
**Additional context**
I  use self-bulit virtual machine and kubernetes not use EC2 instance.

Cloudprober on kubernetes reference [https://cloudprober.org/how-to/run-on-kubernetes/](url)

**Comment by manugarg** [comment]
@lklkxcxc This is very surprising. This is where this error is returned:
https://github.com/google/cloudprober/blob/7608e999daad44c4e079220e441ed9c0feb3f5b1/sysvars/sysvars_ec2.go#L45

But we return this error only if ec2metadata.New(s).Available() returns true. It should return true only on EC2.

Also, cloudprobers on a lot of kubernetes instances, I am surprised you're encountering this error. Anything else about your setup that could be relevant here?

I'll try to understand ec2metadata library more in the meantime.

**Comment by lklkxcxc** [comment]
@manugarg this case cloudprober.cfg show:
```
probe {
  name: "pod-to-endpoints"
  type: HTTP

  targets {
    # RDS (resource discovery service) targets
    # Equivalent to kubectl get ep cloudprober
    rds_targets {
      resource_path: "k8s://endpoints/cloudprober"
    }
  }
  
  http_probe {
    resolve_first: true
    relative_url: "/status"
  }
}

# Run an RDS gRPC server to discover Kubernetes targets.
rds_server {
  provider {
    # For all options, please take a look at:
    # https://github.com/google/cloudprober/blob/master/rds/kubernetes/proto/config.proto#L38
    kubernetes_config {
      endpoints {}
    }
  }
}
```
Virtual machine base on OpenStack not EC2

**Comment by manugarg** [comment]
Based on the ec2metadata code, it seems that Available() call checks for the following URL on the instance:

http://169.254.169.254/latest/meta-data/instance-id

Any possibility that this URL is somehow working on your system?

**Comment by manugarg** [comment]
Ah, it seems that openstack Nova (not sure what Nova is here) provides metadata in EC2 format as well:
https://docs.openstack.org/nova/latest/user/metadata.html#nova-metadata

I am assuming that means http://169.254.169.254/latest/meta-data/instance-id will somehow work on openstack nova as well.

**Comment by manugarg** [comment]
Regardless though, you can disable cloud metadata check completely by providing the following flag to cloudprober:

`--cloud_metadata=none`

**Comment by lklkxcxc** [comment]
@manugarg config "**--cloud_metadata=none**" this problem was sloved.
