### ISSUE TITLE
Support allowed_metrics_regex in Prometheus surfacer

### ISSUE THREAD

**Issue by benner** [google/cloudprober#596]
**Describe the feature you'd like and the problem it will solve**

`cloudwatch` and `stackdriver` surfacers has ability to filter which metrics to emit (`allowed_metrics_regex`). It would be greatge to have same functionality for Prometheus surfacer. This can be useful in situation where Prometeus is for monitoring `cloudprober` itself and target metrics is somewhere else.

**Comment by manugarg** [comment]
I think this is a duplicate of #590. Please feel free to reopen if it is not.

#597 implements a fix for this.
