### ISSUE TITLE
GKE Logging StackDriver Metadata error

### ISSUE THREAD

**Issue by tbuchier** [google/cloudprober#616]
Hello, 

When deploying on GKE, it seems that stackdriver is enabled by default, but failing with metadata error:

```
logger.go:153] [cloudprober.sysvars] Running on GCE. Logs for cloudprober.sysvars will go to Cloud (Stackdriver).
cloudprober.go:182] Error initializing cloudprober. Err: sysvars_gce: error while getting instance from metadata: metadata: GCE metadata "instance/name" not defined
```

GKE 1.20.6 default conf
Using cloudprober/cloudprober:latest
DIGEST:sha256:65fa047385dea20511effb3ec65c01c29cd8851d8f8448a046221e4488aed255

Thanks

**Comment by tbuchier** [comment]
Edit Closing as it's similar to #554 just on the logger instead of surfacer.

I found out that we can disable the logging using the flag: disable_cloud_logging until this issue is fixed

**Comment by manugarg** [comment]
@tbuchier Were you able to find a workaround for this?

**Comment by tbuchier** [comment]
Hello, 

I tried to disable the cloudlogging in case it came from the stackdriver logger setup but still same issue.
I'll have a better look next week :)

**Comment by manugarg** [comment]
You should be able to workaround this by using the flag: --cloud_metadata=none.

**Comment by manugarg** [comment]
FYI: I am implementing a proper fix for this.

**Comment by manugarg** [comment]
I'll implement a proper for this:

- Detect if running on GKE. If running on GKE, don't try to get the instance name when getting cloud metadata.

**Comment by manugarg** [comment]
This should now be fixed, if you use the docker image built from the head (:master).

**Comment by tbuchier** [comment]
Hello, 

It seems that it's still try to access instance metadata (ip)

Using master image i'm now getting:

```
I0714 05:01:24.382697       1 logger.go:152] [cloudprober.sysvars] Running on GCE. Logs for cloudprober.sysvars will go to Cloud (Stackdriver).
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa55197]

goroutine 1 [running]:
cloud.google.com/go/logging.(*Logger).Log(0x0, 0x0, 0x0, 0x0, 0xc8, 0x1265c00, 0xc0000b4250, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/cloud.google.com/go/logging@v1.4.2/logging.go:723 +0x37
github.com/google/cloudprober/logger.(*Logger).log(0xc0004f13b0, 0xc8, 0xc0006bfb40, 0x1, 0x1)
	/home/runner/work/cloudprober/cloudprober/logger/logger.go:245 +0x138
github.com/google/cloudprober/logger.(*Logger).Infof(0xc0004f13b0, 0x15ad4c6, 0x3f, 0xc0006bfc18, 0x1, 0x1)
	/home/runner/work/cloudprober/cloudprober/logger/logger.go:302 +0xa9
github.com/google/cloudprober/logger.(*Logger).EnableStackdriverLogging(0xc0004f13b0, 0x1779d08, 0xc00003e030, 0xc0006bfcc0, 0x1)
	/home/runner/work/cloudprober/cloudprober/logger/logger.go:202 +0x4e5
github.com/google/cloudprober/logger.New(0x1779d08, 0xc00003e030, 0xc000132048, 0x13, 0x1, 0x1573baf, 0x7)
	/home/runner/work/cloudprober/cloudprober/logger/logger.go:153 +0x185
github.com/google/cloudprober/logger.NewCloudproberLog(0x1573baf, 0x7, 0xc00005c800, 0x0, 0xc0006bfd90)
	/home/runner/work/cloudprober/cloudprober/logger/logger.go:137 +0xd8
github.com/google/cloudprober.InitFromConfig(0xc0000da700, 0x645, 0x0, 0x0)
	/home/runner/work/cloudprober/cloudprober/cloudprober.go:139 +0xb4
main.main()
	/home/runner/work/cloudprober/cloudprober/cmd/cloudprober.go:180 +0x7aa
```

I re tried with --disable_cloud_logging and now getting:

```
F0714 05:05:13.685537       1 cloudprober.go:182] Error initializing cloudprober. Err: sysvars_gce: error while getting internal_ip from metadata: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
```

**Comment by manugarg** [comment]
I see what's going on with the first error. We check for "l.logc" being before logging remotely, while "l.logger" is used to log remotely. With the recent change, we created a situation where we are trying to log when l.logger is nil while l.logc is not. Its fix is very simple. I've a PR for it: https://github.com/google/cloudprober/pull/625

Regarding the second error, it seems that more metadata variables are not available on some GKE setups. Which metadata variables are available and which are not is not really documented well. Do you happen to know if there is anything special about your GKE setup? Is metadata access completely disabled?

**Comment by manugarg** [comment]
I think we can go by this list:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gke_mds

**Comment by manugarg** [comment]
It should all be fixed now. @tbuchier, Can you please give it another try? Thanks in advance and sorry for the trouble.

**Comment by tbuchier** [comment]
Thanks a lot, it does work well now :)

At first I was getting some logging permission errors:
```
2021/07/16 12:33:15 logging client: rpc error: code = PermissionDenied desc = The caller does not have permission
2021/07/16 12:33:16 logging client: rpc error: code = PermissionDenied desc = The caller does not have permission
2021/07/16 12:33:51 logging client: rpc error: code = PermissionDenied desc = The caller does not have permission
2021/07/16 12:33:56 logging client: rpc error: code = PermissionDenied desc = The caller does not have permission
...
```

The gke logging is set to system only that's probably why so I just added the disable_cloud_logging flag
