### ISSUE TITLE
Default behaviour of RDS Filter and Probing multiple matched services

### ISSUE THREAD

**Issue by tbuchier** [google/cloudprober#617]
Hello,

It seems that by default rds filter doesn't do an exact match but a startswith match

e.g.:
If I have the namespaces returned in this order by k8s:
* foo-e2etest
* foobar
* foo

The target conf:
```
      targets {
        rds_targets {
          resource_path: "k8s://services"
          filter {
            key: "namespace"
            value: "foo"
          }
        }
      }
```
Will select  `foo-e2etest` and not `foo`.

Could it be matching the exact name instead (and thus foo) ? and if we want to match a pattern that startwith, the user can use `foo.*` 

Also in the case of a multiple service match E.g. if I set `foo.*` Cloudprober will probe the first service only.
Could we have a feature / option to probe all matching service ?

Thanks

**Comment by manugarg** [comment]
We use regex for namespace matching. Sorry it's not super-obvious.

To restrict the namespace match to "foo", you can specify namespace as "^foo$" for now. I think we can add "start" and "end" anchors by default. So if user specifies "foo" that should be automatically interpreted as "^foo$". That will be the usual expectation from user's point of view. Thanks so much for reporting.

> Also in the case of a multiple service match E.g. if I set foo.* Cloudprober will probe the first service only.
> Could we have a feature / option to probe all matching service ?

That should already be the case. We skip a resource only if doesn't match filters. I wonder if it's some other problem. Does your rds_server config specify any namespace at all?

**Comment by tbuchier** [comment]
Yup I've been setting the anchors manually until then.

I'm using the default rds conf:
```
    # Run an RDS gRPC server to discover Kubernetes targets.
    rds_server {
      provider {
        # For all options, please take a look at:
        # https://github.com/google/cloudprober/blob/master/rds/kubernetes/proto/config.proto#L38
        kubernetes_config {
          services {}
          endpoints {}
        }
      }
```

In the probe logs I can see a log message telling me that other matching service are found but ignored

Seems to be due to:

rds/client/client.go
```
	for _, res := range response.GetResources() {
		if oldRes, ok := client.cache[res.GetName()]; ok {
			client.l.Warningf("Got resource (%s) again, ignoring this instance: {%v}. Previous record: %+v.", res.GetName(), res, *oldRes)
			continue
		}
```
This should probably check the combination namespace/name or the ip as my service have the exact same name they are just in different namespaces for example:

namespace:  product | service: redis-server
namespace:  product-beta | service: redis-server
namespace:  product-teste2e | service: redis-server

```
Got resource (redis-server) again, ignoring this instance: {name:"redis-server"  ip:"172.1.1.1"... . Previous record: {ip:172.2.2.2 ....
```

**Comment by manugarg** [comment]
Ah, yes. This makes sense. We enforce unique names for targets. Reason being that in some probe implementations (actually all of them except for the HTTP probe type) metrics are keyed off of target names. It will not be easy to change that.

Do you think creating different probes for different namespaces will be feasible for you? It's probably not very obvious but cloudprober configs have some templating capabilities. For example, you can do the following:

```
{{ range $_, $namespace := mkSlice "product" "product-beta" "product-teste2e" }}
probe {
  name: "probe_redis_{{ $namespace }}"
  type: HTTP
  ....
}
{{ end }}
```

You can see other available config macros here: https://pkg.go.dev/github.com/google/cloudprober@v0.11.2/config

**Comment by tbuchier** [comment]
I see, make sense.

I'll maintain different skaffold profile per env, that maintain the list of namespaces and generate probes using a loop in their Helm template.

Thanks for the explanation
