### ISSUE TITLE
Should prometheus surfacer output delete timestamp?

### ISSUE THREAD

**Issue by gosyang** [google/cloudprober#65]
cloudprober write data in prometheus surfacer end with timstamps, but in some cases,  prometheus can't accept, error like:
`msg="Error on ingesting samples that are too old or are too far into the future"`

like Ben Kochie said in https://groups.google.com/d/msg/prometheus-users/NvLGxFZczJk/8hlYoAEsCwAJ
> It's recommended to omit the timestamp.  The timestamp in the spec is there to allow for federation or importing of data from external TDSBs

Should we delete the timestamp?

**Comment by manugarg** [comment]
@gosyang We possibly can drop the timestamp (or at least make it optional). I think timestamp made sense though as it's the timestamp when probe ran. But, if data is being scraped regularly, it won't make much of a difference.

I wonder why are you getting these errors though. Are there probes that run at a very low frequency or something?

**Comment by gosyang** [comment]
Thanks！
> I wonder why are you getting these errors though

I have some prober in different time zones. I prefer to drop the timestamp and  scrap regularly :smile:

**Comment by manugarg** [comment]
I see. I'll try to add an option to Prometheus surfacer to skip timestamps.

**Comment by manugarg** [comment]
I have a change created (internally). I'll submit it some next week after the review.

**Comment by manugarg** [comment]
@gosyang Latest change adds a config option include_timestamp, that can be used to disable timeout timestamps in prometheus page.

https://github.com/google/cloudprober/commit/d20f0462fb0fba899068ae3cba0dde70b1d58e73
