### ISSUE TITLE
file_targets for probe options

### ISSUE THREAD

**Issue by xenofree** [google/cloudprober#652]
Hi,

Is it possible or will it be possible to configure probe option through file_target like this ?

```
resource {
  name: "10.x.x.x"
  labels {
     key: "hostname"
     value: "xxxxxxxx"
  }
  labels {
     key: "query_type"
     value: A
  }
  labels {
     key: "resolved_domain"
     value: "xxx.xxxxxx.com"
  }
}
```

```
probe {
  name: "dns"
  type: DNS
  targets {
    file_targets {
      file_path: "/data/cloudprober/config.d/dns/targets.yml"
      re_eval_sec: 60
    }
  }
  additional_label {
      key: "hostname"
      value: "@target.label.hostname@"
  }
  additional_label {
      key: "resolved_domain"
      value: "@target.label.resolved_domain@"
  }
  dns_probe {
    query_type: @target.label.query_type@
    resolved_domain: "@target.label.resolved_domain@"
  }
  interval_msec: 60000  # 60s
  timeout_msec: 10000   # 10s
}
```

**Comment by manugarg** [comment]
This should work. @xenofree, is it not working?

**Comment by xenofree** [comment]
This is not working.

For query type I have this kind of issue.

```
  dns_probe {
    query_type: @target.label.query_type@
    resolved_domain: "@target.label.resolved_domain@"
  }
```

```
Error initializing cloudprober. Err: line 67: unexpected byte 0x40
```

```
  dns_probe {
    query_type: "@target.label.query_type@"
    resolved_domain: "@target.label.resolved_domain@"
  }
```

```
Err: line 67: invalid enum: "@target.label.query_type@"
```

And resolved_domain don't seems to be evauated.

```
error in response ;; opcode: QUERY, status: NXDOMAIN, id: 61782
;; QUESTION SECTION:
;\@target.label.resolved_domain\@.      IN       A
```

**Comment by manugarg** [comment]
Oops. Sorry, I was wrong. I missed that you were using labels in the probe config. This will not work.

It's going to be hard to implement a generic label replacement mechanism.

The way it works in HTTP probe is:
- If "relative_url" or "host" is not defined in the probe config, and target has these labels, it automatically uses these labels.

We can do something similar for DNS probe.

**Comment by manugarg** [comment]
@xenofree Please see the announcement here: #679. Active development of this repository is moving to github.com/cloudprober/cloudprober. Unfortunately, we'll have to close all the issues here, and file them again. Can you please do that. Thanks!

**Comment by manugarg** [comment]
Moved here: https://github.com/cloudprober/cloudprober/issues/26.
