### ISSUE TITLE
Expose parsed config through a web URL (/config)

### ISSUE THREAD

**Issue by manugarg** [google/cloudprober#72]

**Comment by stevemcghee** [comment]
curious if the goal is to result in something like a green/red timeline, similar to other .. probing .. software? :)

**Comment by manugarg** [comment]
@stevemcghee Sorry for the late response, I was on vacation. Getting red/green timelines will be really nice but I wasn't exactly aiming for that. Cloudprober doesn't have transactional model for UDP probe for example -- we just send some packets and collect responses asynchronously. Ping probe will probably also move to the same model. It will be easier to show timeline with history for HTTP probe.

I was thinking of starting with some basic information first in the UI. We can show the trend for all probe types and history only for HTTP probes.
