### ISSUE TITLE
Propose: Dockerfile w/ ENTRYPOINT & CMD

### ISSUE THREAD

**Issue by DazWilkin** [google/cloudprober#88]
Please consider revising project's `Dockerfile` to use `ENTRYPOINT` (to start `cloudprober`) and `CMD` to default the flags to `--logtostderr` like so:

```Dockerfile
...
ENTRYPOINT ["/cloudprober"]
CMD ["--logtostderr"]
```
Currently, the container does not permit e.g. arbitrary config files:
```
docker run \
--publish=9313:9313 \
--volume=$PWD/cloudprober.google.cfg:/cloudprober.cfg cloudprober/cloudprober \
--config_file /cloudprober.cfg \
--logtostderr
```
produces:
```container_linux.go:265: starting container process caused "exec: \"--config_file\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"--config_file\": executable file not found in $PATH".
ERRO[0000] error waiting for container: context canceled 
```

With the change, the `docker` command works.

This change helps e.g. run `cloudprober` on Kubernetes

**Comment by manugarg** [comment]
Thanks for this suggestion @DazWilkin. Using ENTRYPOINT instead of CMD makes sense.
