### ISSUE TITLE
FR: Add (useful) "/config" endpoint to documentation

### ISSUE THREAD

**Issue by DazWilkin** [google/cloudprober#95]
Hunting around the code for a solution to an issue, I discovered the "/config" endpoint.

This is a useful endpoint for confirming cloudprober's current configuration.

Please consider including it (I think it's not currently) in the documentation.

**Comment by manugarg** [comment]
Thanks for the feedback @DazWilkin. You're right. It's currently not included in the documentation. I'll add it.

**Comment by manugarg** [comment]
This is done now. Added a verification section to the "Getting Started" page: https://cloudprober.org/getting-started/
